# **Fase 1 — Configuración inicial**

In [ ]:
# Librerías
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Cargar el dataset
df_energIA = pd.read_csv('/content/energy_consumption (1).csv')

In [ ]:
df_energIA.head()

,hogar_id,tipo_inmueble,metros_cuadrados,antiguedad_vivienda,zona_fria,calidad_aislamiento,fuente_calefaccion,fuente_agua_caliente,consumo_kwh,uso_horario_pico,horas_alto_consumo,cantidad_equipos,categoria
0,Hogar_0001,Departamento,1269,61,No,Muy Baja,Solar,Electricidad,363.4,Si,14,19,Moderado
1,Hogar_0002,Pyme,928,16,Si,Media,Electricidad,Otros,730.2,No,5,92,Moderado
2,Hogar_0003,Comercio,188,65,No,Media,Otros,Otros,298.7,Si,7,39,Moderado
3,Hogar_0004,Departamento,2000,5,Si,Muy Baja,Electricidad,Solar,542.9,Si,23,85,Moderado
4,Hogar_0005,Casa,1269,57,No,Muy Alta,Electricidad,Electricidad,433.4,Si,13,90,Moderado

# **Fase 2 — Información general**

In [ ]:
print(f'Este dataset está conformado por {df_energIA.shape[1]} columnas y {df_energIA.shape[0]} registros únicos.')

Este dataset está conformado por 13 columnas y 2000 registros únicos.

In [ ]:
df_energIA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hogar_id              2000 non-null   object
 1   tipo_inmueble         2000 non-null   object
 2   metros_cuadrados      2000 non-null   int64
 3   antiguedad_vivienda   2000 non-null   int64
 4   zona_fria             2000 non-null   object
 5   calidad_aislamiento   2000 non-null   object
 6   fuente_calefaccion    2000 non-null   object
 7   fuente_agua_caliente  2000 non-null   object
 8   consumo_kwh           2000 non-null   float64
 9   uso_horario_pico      2000 non-null   object
 10  horas_alto_consumo    2000 non-null   int64
 11  cantidad_equipos      2000 non-null   int64
 12  categoria             2000 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 203.3+ KB

# **Fase 3 — Revisión tipos de datos**

In [ ]:
df_energIA.dtypes

hogar_id                 object
tipo_inmueble            object
metros_cuadrados          int64
antiguedad_vivienda       int64
zona_fria                object
calidad_aislamiento      object
fuente_calefaccion       object
fuente_agua_caliente     object
consumo_kwh             float64
uso_horario_pico         object
horas_alto_consumo        int64
cantidad_equipos          int64
categoria                object
dtype: object

In [ ]:
# Variables tipo object a tipo string
col_object_a_string = [
    "hogar_id",
    "tipo_inmueble",
    "calidad_aislamiento",
    "fuente_calefaccion",
    "fuente_agua_caliente",
    "categoria"
]

df_energIA[col_object_a_string] = df_energIA[col_object_a_string].astype("string")

# Variables tipo object a tipo booleano
df_energIA["zona_fria"] = df_energIA["zona_fria"].map({"Si": True, "No": False})
df_energIA["uso_horario_pico"] = df_energIA["uso_horario_pico"].map({"Si": True, "No": False})

In [ ]:
df_energIA.dtypes

hogar_id                string[python]
tipo_inmueble           string[python]
metros_cuadrados                 int64
antiguedad_vivienda              int64
zona_fria                         bool
calidad_aislamiento     string[python]
fuente_calefaccion      string[python]
fuente_agua_caliente    string[python]
consumo_kwh                    float64
uso_horario_pico                  bool
horas_alto_consumo               int64
cantidad_equipos                 int64
categoria               string[python]
dtype: object

# **Fase 4 — Revisión valores**

In [ ]:
# Valores nulos
df_energIA.isnull().sum()

hogar_id                0
tipo_inmueble           0
metros_cuadrados        0
antiguedad_vivienda     0
zona_fria               0
calidad_aislamiento     0
fuente_calefaccion      0
fuente_agua_caliente    0
consumo_kwh             0
uso_horario_pico        0
horas_alto_consumo      0
cantidad_equipos        0
categoria               0
dtype: int64

In [ ]:
# Valores duplicados
df_energIA.duplicated().sum()

np.int64(0)

# **Fase 5 — Estadística descriptiva**

In [ ]:
# Variables categóricas
df_energIA.describe(include='string[python]')

,hogar_id,tipo_inmueble,calidad_aislamiento,fuente_calefaccion,fuente_agua_caliente,categoria
count,2000,2000,2000,2000,2000,2000
unique,2000,4,5,3,3,3
top,Hogar_1985,Casa,Media,Electricidad,Electricidad,Moderado
freq,1,705,676,901,901,1269

In [ ]:
# Variables numéricas
df_energIA.describe()

,metros_cuadrados,antiguedad_vivienda,consumo_kwh,horas_alto_consumo,cantidad_equipos
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1047.917500,76.568000,501.675600,12.070500,50.628500
std,575.892368,43.391725,287.520086,7.179157,28.778805
min,26.000000,0.000000,0.200000,0.000000,1.000000
25%,541.750000,38.750000,253.075000,6.000000,27.000000
50%,1062.000000,78.000000,506.000000,12.000000,50.000000
75%,1574.000000,114.000000,747.500000,18.000000,76.000000
max,2000.000000,150.000000,999.900000,24.000000,100.000000

# **Fase 6 — Análisis variables categóricas**

In [ ]:
df_energIA.select_dtypes(include=['string[python]']).columns

Index(['hogar_id', 'tipo_inmueble', 'calidad_aislamiento',
       'fuente_calefaccion', 'fuente_agua_caliente', 'categoria'],
      dtype='object')

In [ ]:
# Variable tipo_inmueble
conteo = df_energIA["tipo_inmueble"].value_counts().reset_index()
conteo.columns = ["tipo_inmueble", "cantidad"]

fig = px.bar(
    conteo,
    x="tipo_inmueble",
    y="cantidad",
    title="Cantidad de hogares por tipo de inmueble",
    color="tipo_inmueble",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    xaxis_title="Tipo de inmueble",
    yaxis_title="Cantidad")

fig.show()

In [ ]:
# Variable calidad_aislamiento
orden = ["Muy Alta", "Alta", "Media", "Baja", "Muy Baja"]
conteo = df_energIA["calidad_aislamiento"].value_counts().reindex(orden).reset_index()
conteo.columns = ["calidad_aislamiento", "cantidad"]

fig = px.bar(
    conteo,
    x="calidad_aislamiento",
    y="cantidad",
    title="Calidad del aislamiento",
    color="calidad_aislamiento",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    xaxis_title="Calidad del aislamiento",
    yaxis_title="Cantidad",
    xaxis=dict(categoryorder="array",
               categoryarray=orden))

fig.show()

In [ ]:
# Variable fuente_calefaccion
conteo = df_energIA["fuente_calefaccion"].value_counts().reset_index()
conteo.columns = ["fuente_calefaccion", "cantidad"]

fig = px.bar(
    conteo,
    x="fuente_calefaccion",
    y="cantidad",
    title="Tipos de fuentes de calefacción",
    color="fuente_calefaccion",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    xaxis_title="Tipos de calefacción",
    yaxis_title="Cantidad")

fig.show()

In [ ]:
# Variable fuente_agua_caliente
conteo = df_energIA["fuente_agua_caliente"].value_counts().reset_index()
conteo.columns = ["fuente_agua_caliente", "cantidad"]

fig = px.bar(
    conteo,
    x="fuente_agua_caliente",
    y="cantidad",
    title="Tipos de calefacción para agua caliente",
    color="fuente_agua_caliente",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    xaxis_title="Tipos de calefacción para agua caliente",
    yaxis_title="Cantidad")

fig.show()

In [ ]:
# Variable categoria
orden = ["Eficiente", "Moderado", "Ineficiente"]
conteo = df_energIA["categoria"].value_counts().reindex(orden).reset_index()
conteo.columns = ["categoria", "cantidad"]

fig = px.bar(
    conteo,
    x="categoria",
    y="cantidad",
    title="Categoría de eficiencia energética",
    color="categoria",
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    xaxis_title="Categoría",
    yaxis_title="Cantidad",
    xaxis=dict(categoryorder="array",
               categoryarray=orden))

fig.show()

# **Fase 7 — Análisis variables numéricas**

In [ ]:
df_energIA.select_dtypes(exclude=['string[python]']).columns

Index(['metros_cuadrados', 'antiguedad_vivienda', 'zona_fria', 'consumo_kwh',
       'uso_horario_pico', 'horas_alto_consumo', 'cantidad_equipos'],
      dtype='object')

In [ ]:
# Variable metros_cuadrados
fig = px.box(
    df_energIA,
    x="metros_cuadrados",
    title="Distribución de los metros cuadrados"
    )

fig.update_traces(marker_color="rgb(152,78,163)")
fig.show()

In [ ]:
# Variable antiguedad_vivienda
fig = px.box(
    df_energIA,
    x="antiguedad_vivienda",
    title="Antigüedad de la vivienda",
)

fig.update_traces(marker_color="rgb(152,78,163)")
fig.show()

In [ ]:
# Variable zona_fria
fig = px.box(
    df_energIA,
    y="zona_fria",
    x="consumo_kwh",
    title="Consumo en zona fría",
    color="zona_fria",
    color_discrete_map={True: "rgb(152,78,163)", False: "rgb(255,123,0)"},
)
fig.show()

In [ ]:
# Variable horas_alto_consumo
fig = px.box(
    df_energIA,
    x="horas_alto_consumo",
    title="Horas de alto consumo"
)

fig.update_traces(marker_color="rgb(152,78,163)")
fig.show()

In [ ]:
# Variable zona_fria
fig = px.box(
    df_energIA,
    y="uso_horario_pico",
    x="consumo_kwh",
    title="Consumo según uso en horario pico",
    color="uso_horario_pico",
    color_discrete_map={True: "rgb(152,78,163)", False: "rgb(255,123,0)"},
)

fig.show()

In [ ]:
# Variable cantidad_equipos
fig = px.box(
    df_energIA,
    x="cantidad_equipos",
    title="Cantidad de equipos eléctricos"
)

fig.update_traces(marker_color="rgb(152,78,163)")
fig.show()

In [ ]:
def boxplot_variable(df, variable, titulo, etiqueta_y):
    fig = px.box(
        df,
        x=variable,
        title=titulo
    )

    fig.update_layout(
        xaxis_title="",
        yaxis_title=etiqueta_y
    )
    fig.update_traces(marker_color="rgb(152,78,163)")
    fig.show()

In [ ]:
boxplot_variable(
    df_energIA,
    "consumo_kwh",
    "Distribución del consumo eléctrico",
    "Consumo (kWh)"
)